# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'WeatherStation' do

    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON', '~> 3.1'
    pod 'Charts', '~> 3.0'
    pod 'MagicalRecord', '~> 2.3'
    pod 'PageMenu', :git => 'https://github.com/kdovbush/PageMenu'
end
